DROP TABLE IF EXISTS Usuario;

DROP TABLE IF EXISTS Empleado;

DROP TABLE IF EXISTS Archivo;

DROP TABLE IF EXISTS Mensaje;


DROP TABLE IF EXISTS Beneficiario;

DROP TABLE IF EXISTS Vacacion;

DROP TABLE IF EXISTS Descuento;

DROP TABLE IF EXISTS Movimiento;

DROP TABLE IF EXISTS Permiso;

DROP TABLE IF EXISTS Baja;

DROP TABLE IF EXISTS Trabajador;

DROP TABLE IF EXISTS Pase;

DROP TABLE IF EXISTS Reingreso;

DROP TABLE IF EXISTS Expediente;

DROP TABLE IF EXISTS Gastos;

DROP TABLE IF EXISTS Roles;

DROP TABLE IF EXISTS Correos;

DROP TABLE IF EXISTS Configuracion;

DROP TABLE IF EXISTS Historial_Plaza;

DROP TABLE IF EXISTS Plaza;

DROP TABLE IF EXISTS Puesto;

DROP TABLE IF EXISTS Departamento;

DROP TABLE IF EXISTS Prenomina;

DROP TABLE IF EXISTS Periodo;

CREATE TABLE Periodo(
	id_periodo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL
);

CREATE TABLE Prenomina(
	id_prenomina INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	del DATE NOT NULL,
	al DATE NOT NULL,
	url VARCHAR(50),
	observacion VARCHAR(255),
	id_periodo VARCHAR(50) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Configuracion(
	id_configuracion INT PRIMARY KEY AUTO_INCREMENT,
	logo VARCHAR(100),
	nombre VARCHAR(100)
);

CREATE TABLE Correos(
	id_correo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	receptor VARCHAR(13) NOT NULL,
	emisor VARCHAR(13) NOT NULL,
	mensaje VARCHAR(255) NOT NULL,
	url VARCHAR(50),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Roles(
	rol INT NOT NULL,
	RFC VARCHAR(13) NOT NULL PRIMARY KEY,
	descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE Gastos(
	id_gastos INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	concepto VARCHAR(500) NOT NULL,
	fecha DATE NOT NULL,
	monto DECIMAL(8,2) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	url VARCHAR(50),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Expediente(
	RFC VARCHAR(13) NOT NULL PRIMARY KEY,
	acta VARCHAR(100) NULL,
	antecedentes VARCHAR(100) NULL,
	disciplinarios VARCHAR(100) NULL,
	curp VARCHAR(100) NULL,
	curriculum VARCHAR(100) NULL,
	identificacion VARCHAR(100) NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Reingreso(
	id_reingreso INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	inicio DATE NOT NULL,
	observaciones VARCHAR(500),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Usuario(
	RFC VARCHAR(13) PRIMARY KEY NOT NULL,
	categoria VARCHAR(10) NOT NULL,
	contrasenia VARCHAR(30) NOT NULL,
	email VARCHAR(50),
	telefono VARCHAR(20),
	urlFoto VARCHAR(100),
	nombre VARCHAR(100),
	estado VARCHAR(5) DEFAULT 'alta',
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Empleado(
	id_empleado INT,
	RFC VARCHAR(13),
	CURP VARCHAR(18),
	fechaRelLab VARCHAR(10),
	banca VARCHAR(18),
	afiliacion VARCHAR(20),
	apellidop VARCHAR(50),
	apellidom VARCHAR(50),
	nombres VARCHAR(50),
	id_trabajador INT,
	id_periodo INT,
	id_puesto INT,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Archivo(
	id_archivo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	dias_pago INT NOT NULL,
	url VARCHAR(50) NOT NULL,
	fecha_pago DATE NOT NULL,
	del DATE NOT NULL,
	al DATE NOT NULL,
	puesto VARCHAR(100) NOT NULL,
	id_periodo INT NOT NULL,
	departamento VARCHAR(100) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Mensaje(
	id_mensaje INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	mensaje VARCHAR(500),
	emisor VARCHAR(13) NOT NULL,
	receptor VARCHAR(13) NOT NULL,
	estado INT NOT NULL DEFAULT 0,
	url VARCHAR(50),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Beneficiario(
	id_beneficiario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	beneficiario VARCHAR(50) NOT NULL,
	parentesco VARCHAR(20) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	url VARCHAR(50)
);

CREATE TABLE Permiso(
	id_permiso INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	dias INT NOT NULL,
	del DATE NOT NULL,
	al DATE NOT NULL,
	categoria INT NOT NULL,
	descripcion VARCHAR(500),
	url VARCHAR(50),
	materno INT NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Vacacion(
	id_vacacion INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	dias INT NOT NULL,
	del DATE NOT NULL,
	al DATE NOT NULL,
	descripcion VARCHAR(500),
	url VARCHAR(50),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Descuento(
	id_descuento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	dias INT NOT NULL,
	fecha DATE NOT NULL,
	fechas VARCHAR(500) NOT NULL,
	motivo VARCHAR(500) NOT NULL,
	url VARCHAR(50),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Movimiento(
	id_movimiento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	puesto VARCHAR(100) NOT NULL,
	departamento VARCHAR(100) NOT NULL,
	plaza INT NOT NULL,
	tipoTrabajador VARCHAR(100) NOT NULL,
	url VARCHAR(50),
	puestoAnterior VARCHAR(100) NOT NULL,
	departamentoAnterior VARCHAR(100) NOT NULL,
	tipoTrabajadorAnterior VARCHAR(100) NOT NULL,
	plazaAnterior INT NOT NULL,
	observacion VARCHAR(300),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Baja(
	id_baja INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	razon VARCHAR(100) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	dias INT DEFAULT 0
);

CREATE TABLE Departamento(
	id_departamento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Puesto(
	id_puesto INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	id_departamento INT NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(id_departamento) REFERENCES Departamento(id_departamento)
);

CREATE TABLE Trabajador(
	id_trabajador INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Pase(
	id_pase INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	hora VARCHAR(10) NOT NULL,
	categoria INT NOT NULL,
	observacion VARCHAR(500),
	url VARCHAR(50),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Plaza(
	id_plaza INT PRIMARY KEY AUTO_INCREMENT,
	id_puesto INT NOT NULL,
	RFC VARCHAR(13),
	dias INT NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	estado INT DEFAULT 1,
	FOREIGN KEY(id_puesto) REFERENCES Puesto(id_puesto)
);

CREATE TABLE Historial_Plaza(
	id_historial_plaza INT PRIMARY KEY AUTO_INCREMENT,
	id_plaza INT NOT NULL,
	RFC VARCHAR(13) NOT NULL,
	fecha_inicio DATE NOT NULL,
	fecha_fin DATE,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(id_plaza) REFERENCES Plaza(id_plaza) ON DELETE CASCADE
);





INSERT INTO Usuario(categoria, contrasenia, nombre, RFC, email) VALUES ('admin', 'admin', 'Administrador', 'admin','admin@admin.com');
INSERT INTO Usuario(categoria, contrasenia, nombre, RFC, email) VALUES ('admin', 'nomina', 'Consulta Nomina', 'nomina','admin@admiin.com');

INSERT INTO Trabajador(nombre) VALUES('BASE');

INSERT INTO Trabajador(nombre) VALUES('CONFIANZA');

INSERT INTO Trabajador(nombre) VALUES('HONORARIOS');

INSERT INTO Trabajador(nombre) VALUES('EVENTUAL');

INSERT INTO Trabajador(nombre) VALUES('SINDICALIZADO');

INSERT INTO Configuracion(logo,nombre) VALUES("logo.png", "COMONFORT");

INSERT INTO Periodo(nombre) VALUES("CATORCENAL");
INSERT INTO Periodo(nombre) VALUES("MENSUAL");
INSERT INTO Periodo(nombre) VALUES("OTRA PERIODICIDAD");

INSERT INTO Roles(rol,RFC, descripcion) VALUES('1', 'admin', 'administrador principal');
INSERT INTO Roles(rol,RFC, descripcion) VALUES('1', 'nomina', 'administrador principal');
INSERT INTO Roles(rol,RFC, descripcion) VALUES('3', 'admin2', 'carga las nominas');
INSERT INTO Roles(rol,RFC, descripcion) VALUES('2', 'admin3', 'carga archivos del expediente');
