DROP TABLE IF EXISTS Usuario;

DROP TABLE IF EXISTS Archivo;

DROP TABLE IF EXISTS Mensaje;

DROP TABLE IF EXISTS Chat;

DROP TABLE IF EXISTS Beneficiario;

DROP TABLE IF EXISTS Vacacion;

DROP TABLE IF EXISTS Descuento;

DROP TABLE IF EXISTS Movimiento;

DROP TABLE IF EXISTS Permiso;

DROP TABLE IF EXISTS Baja;

DROP TABLE IF EXISTS Trabajador;

DROP TABLE IF EXISTS Pase;

DROP TABLE IF EXISTS Reingreso;

DROP TABLE IF EXISTS Expediente;

DROP TABLE IF EXISTS Gastos;

DROP TABLE IF EXISTS Roles;

DROP TABLE IF EXISTS Correos;

DROP TABLE IF EXISTS Configuracion;

DROP TABLE IF EXISTS Historial_Plaza;

DROP TABLE IF EXISTS Plaza;

DROP TABLE IF EXISTS Puesto;

DROP TABLE IF EXISTS Departamento;

CREATE TABLE Configuracion(
	id_configuracion INT(1) PRIMARY KEY AUTO_INCREMENT,
	logo VARCHAR(255),
	nombre VARCHAR(255)
);

INSERT INTO Configuracion(logo,nombre) VALUES("logo.png", "COMONFORT");

CREATE TABLE Correos(
	id_correo INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	receptor VARCHAR(13) NOT NULL,
	emisor VARCHAR(13) NOT NULL,
	mensaje VARCHAR(255) NOT NULL,
	url VARCHAR(100),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Roles(
	rol INT(5) NOT NULL,
	RFC VARCHAR(13) NOT NULL PRIMARY KEY,
	descripcion VARCHAR(50) NOT NULL
);

INSERT INTO Roles(rol,RFC, descripcion) VALUES('1', 'admin', 'administrador principal');
INSERT INTO Roles(rol,RFC, descripcion) VALUES('3', 'admin2', 'carga las nominas');
INSERT INTO Roles(rol,RFC, descripcion) VALUES('2', 'admin3', 'carga archivos del expediente');

CREATE TABLE Gastos(
	id_gastos INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	concepto VARCHAR(500) NOT NULL,
	fecha DATE NOT NULL,
	monto DECIMAL(8,2) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	url VARCHAR(200),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Expediente(
	RFC VARCHAR(13) NOT NULL PRIMARY KEY,
	acta VARCHAR(100) NULL,
	antecedentes VARCHAR(100) NULL,
	disciplinarios VARCHAR(100) NULL,
	curp VARCHAR(100) NULL,
	curriculum VARCHAR(100) NULL,
	identificacion VARCHAR(100) NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Reingreso(
	id_reingreso INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	inicio DATE NOT NULL,
	observaciones VARCHAR(500),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Usuario(
	id_usuario INT(5) NOT NULL,
	categoria VARCHAR(10) NOT NULL,
	contrasenia VARCHAR(30) NOT NULL,
	email VARCHAR(50),
	telefono VARCHAR(20),
	urlFoto VARCHAR(200),
	nombre VARCHAR(100),
	estado VARCHAR(5) DEFAULT 'alta',
	RFC VARCHAR(13) PRIMARY KEY NOT NULL,
	CURP VARCHAR(18),
	fechaRelLab VARCHAR(10),
	puesto VARCHAR(100),
	departamento VARCHAR(100),
	banca VARCHAR(18),
	afiliacion VARCHAR(20),
	apellidop VARCHAR(50),
	apellidom VARCHAR(50),
	nombres VARCHAR(50),
	archivo VARCHAR(200),
	tipoTrabajador VARCHAR(30),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Archivo(
	id_archivo INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT(5) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	fecha_subida VARCHAR(10) NOT NULL,
	url VARCHAR(100) NOT NULL,
	dia INT(2) NOT NULL,
	mes INT(2) NOT NULL,
	ano INT(4) NOT NULL,
	fecha_pago VARCHAR(10) NOT NULL,
	nombreEmpleado VARCHAR(100) NOT NULL,
	RFC VARCHAR(18) NOT NULL,
	CURP VARCHAR(18) NOT NULL,
	fechaRelLab VARCHAR(10) NOT NULL,
	puesto VARCHAR(100) NOT NULL,
	departamento VARCHAR(100) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Mensaje(
	id_mensaje INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_chat INT(5) NOT NULL,
	mensaje VARCHAR(700) NOT NULL,
	fecha VARCHAR(30) NOT NULL,
	emisor VARCHAR(13) NOT NULL,
	receptor VARCHAR(13) NOT NULL,
	estado INT(1) NOT NULL DEFAULT 0,
	url VARCHAR(200),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Chat(
	id_chat INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	titulo VARCHAR(100) NOT NULL,
	fecha VARCHAR(30) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Beneficiario(
	id_beneficiario INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	beneficiario VARCHAR(50) NOT NULL,
	parentesco VARCHAR(20) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	url VARCHAR(200)
);

CREATE TABLE Permiso(
	id_permiso INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	dias INT(5) NOT NULL,
	del DATE NOT NULL,
	al DATE NOT NULL,
	categoria INT(1) NOT NULL,
	descripcion VARCHAR(500),
	url VARCHAR(200),
	materno INT(1) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Vacacion(
	id_vacacion INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	dias INT(5) NOT NULL,
	del DATE NOT NULL,
	al DATE NOT NULL,
	descripcion VARCHAR(500),
	url VARCHAR(100),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Descuento(
	id_descuento INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	dias INT(5) NOT NULL,
	fecha DATE NOT NULL,
	fechas VARCHAR(500) NOT NULL,
	motivo VARCHAR(500) NOT NULL,
	url VARCHAR(100),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Movimiento(
	id_movimiento INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	puesto VARCHAR(100) NOT NULL,
	departamento VARCHAR(100) NOT NULL,
	url VARCHAR(100),
	puestoAnterior VARCHAR(100) NOT NULL,
	departamentoAnterior VARCHAR(100) NOT NULL,
	tipoTrabajadorAnterior VARCHAR(100) NOT NULL,
	observacion VARCHAR(100),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Baja(
	id_baja INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	razon VARCHAR(100) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	dias INT(1) DEFAULT 0
);

CREATE TABLE Departamento(
	id_departamento INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Puesto(
	id_puesto INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	id_departamento INT(5) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(id_departamento) REFERENCES Departamento(id_departamento)
);

CREATE TABLE Trabajador(
	id_trabajador INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Pase(
	id_pase INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RFC VARCHAR(13) NOT NULL,
	fecha DATE NOT NULL,
	hora VARCHAR(10) NOT NULL,
	categoria INT(1) NOT NULL,
	observacion VARCHAR(500),
	url VARCHAR(200),
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Plaza(
	id_plaza INT(5) PRIMARY KEY AUTO_INCREMENT,
	id_puesto INT(5) NOT NULL,
	RFC INT(5),
	dias INT(3) NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(id_puesto) REFERENCES Puesto(id_puesto)
);

CREATE TABLE Historial_Plaza(
	id_historial_plaza INT(5) PRIMARY KEY AUTO_INCREMENT,
	id_plaza INT(5) NOT NULL,
	fecha_inicio DATE NOT NULL,
	fecha_fin DATE NOT NULL,
	elaboracion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(id_plaza) REFERENCES Plaza(id_plaza)
);


INSERT INTO Usuario(id_usuario, categoria, contrasenia, nombre, RFC) VALUES ('0', 'admin', 'admin', 'Administrador', 'admin');

INSERT INTO Trabajador(nombre) VALUES('BASE');

INSERT INTO Trabajador(nombre) VALUES('CONFIANZA');

INSERT INTO Trabajador(nombre) VALUES('HONORARIOS');

INSERT INTO Trabajador(nombre) VALUES('EVENTUAL');

INSERT INTO Trabajador(nombre) VALUES('SINDICALIZADO');
